name: IA Code Reviewer

on:
  pull_request:
    branches: [ staging ]
    types: [ opened, synchronize ]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install google-genai PyGithub

      - name: Executar Review da IA e Validar Veredito
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python -c "
          import os, sys, github
          from google import genai

          auth = github.Auth.Token(os.getenv('GITHUB_TOKEN'))
          gh = github.Github(auth=auth)
          repo = gh.get_repo(os.getenv('REPO_NAME'))
          pr = repo.get_pull(int(os.getenv('PR_NUMBER')))

          diffs = []
          for file in pr.get_files():
              diffs.append(f'Arquivo: {file.filename}\n{file.patch}')
          diff_text = '\n\n'.join(diffs)

          client = genai.Client(api_key=os.getenv('GEMINI_API_KEY'))
          models_to_try = ['gemini-3.5-flash-lite','gemini-3.7-flash', 'gemini-1.5-flash']
          response = None

          prompt = (
              'Você é um Code Reviewer Senior. Analise o Diff abaixo.\n'
              'Obrigatório: Inicie a resposta EXATAMENTE com \"STATUS: APROVADO\" ou \"STATUS: REPROVADO\" na primeira linha.\n'
              'Só aprove se o código não contiver bugs graves, falhas de segurança ou falta de tratamento de exceções.\n\n'
              f'{diff_text}'
          )

          for model_name in models_to_try:
              try:
                  response = client.models.generate_content(model=model_name, contents=prompt)
                  break
              except Exception as e:
                  print(f'Erro no {model_name}: {e}')

          if not response or not response.text:
              sys.exit('Falha: nenhum modelo respondeu.')

          # Posta a análise nos comentários
          pr.create_issue_comment(f'### 🤖 Análise do Agente de IA\n\n{response.text}')

          # Reprova o PR (interrompe a pipeline) se o veredito for negativo
          if 'STATUS: REPROVADO' in response.text.upper():
              print('❌ A IA reprovou este Pull Request.')
              sys.exit(1)
          else:
              print('✅ A IA aprovou este Pull Request.')
          "